V0.50.1 patched
Switcheo/cosmos-sdk pull request #438
Opened 2023-12-07 05:03 UTC by yan-soon

key changes:
- revert new cosmos-sdk change where `multiSend` can only have one sender (https://github.com/cosmos/cosmos-sdk/issues/12601)
- revert new cosmos-sdk change where `send` and `multiSend` typeAsserts the bank keeper to be of type `BaseKeeper` (this type assertion has issues with our implementation as our bank keeper is customised due to the x/alliance module, where the keeper is a wrapper of the original `x/bank BaseKeeper`, resulting in the type assertion check failing 
https://github.com/Switcheo/cosmos-sdk/pull/438/commits/102b3f27ed74d6b62851c91c6444c887a872d6a9

2023-12-14 07:58 UTC, RavenXce commented
reverting msgmultisend is not safe

2024-01-08 11:04 UTC, RavenXce requested changes

2024-01-08 11:04 UTC, RavenXce commented on types/module/module.go
> +				startTime := time.Now()
huh is start here correct..?

2024-01-08 11:04 UTC, RavenXce commented on types/module/module.go
> +				m.beforeModuleEndBlock(moduleName)
no end block telemetry..?

2024-01-08 11:04 UTC, RavenXce commented on types/errors/abci.go
> -		Events:    events,
does this change things for us?

2024-01-08 11:04 UTC, RavenXce commented on store/snapshots/store.go
> +		}
what patch is this?

2024-01-08 11:04 UTC, RavenXce commented on store/pruning/types/options.go
> +	PruningStartHeight uint64
what patch is this?

2024-01-08 11:04 UTC, RavenXce commented on store/pruning/types/options.go
> +	PruningOptionStartHeight = "pruning-start-height"
what patch is this?

2024-01-08 11:04 UTC, RavenXce commented on server/config/toml.go
> +oracle-address = "{{ .API.OracleAddress }}"
y are there oracle stuff here?

2024-01-08 11:04 UTC, RavenXce commented on server/config/config.go
> +			OracleAddress:      DefaultOracleAPIAddress,
y are there oracle stuff here?

2024-01-08 11:04 UTC, RavenXce commented on server/config/config.go
> +	OracleAddress string `mapstructure:"oracle-address"`
y are there oracle stuff here?

2024-01-19 10:10 UTC, yan-soon commented on server/config/toml.go
> +oracle-address = "{{ .API.OracleAddress }}"
https://github.com/yan-soon/cosmos-sdk/commit/48e32471b66a86a806e614e320af1df6402d7398

2024-01-19 10:11 UTC, yan-soon commented on server/config/config.go
> +			OracleAddress:      DefaultOracleAPIAddress,
https://github.com/switcheo/cosmos-sdk/commit/48e32471b66a86a806e614e320af1df6402d7398

2024-01-19 10:11 UTC, yan-soon commented on server/config/config.go
> +	OracleAddress string `mapstructure:"oracle-address"`
https://github.com/switcheo/cosmos-sdk/commit/48e32471b66a86a806e614e320af1df6402d7398

2024-01-19 10:16 UTC, yan-soon commented on baseapp/abci.go
> +func (app *BaseApp) BeginBlock(req *abci.RequestFinalizeBlock) (res sdk.BeginBlock, err error) {
resolved in https://github.com/Switcheo/cosmos-sdk/pull/438/commits/2bb73567da711a92545f5b598e06bc8c37d5d18d

2024-01-19 10:16 UTC, yan-soon commented on x/evidence/abci.go
> +func BeginBlocker(ctx sdk.Context, req abci.RequestBeginBlock, k keeper.Keeper) {
resolved in https://github.com/Switcheo/cosmos-sdk/pull/438/commits/2bb73567da711a92545f5b598e06bc8c37d5d18d

2024-01-19 10:16 UTC, yan-soon commented on x/distribution/types/params.go
> +func validateLiquidityProviderReward(i interface{}) error {
resolved in https://github.com/Switcheo/cosmos-sdk/pull/438/commits/2bb73567da711a92545f5b598e06bc8c37d5d18d

2024-01-19 10:19 UTC, yan-soon commented on x/bank/keeper/msg_server.go
> +	// if base, ok := k.Keeper.(*BaseKeeper); ok {
the type assertion check : `if base, ok := k.Keeper.(*BaseKeeper); ok {`
of the custom wrapper alliance bank module to `*BaseKeeper` fails

2024-06-11 04:32 UTC, closed without merging